/**
 * A wrapper around initialize, sign, and verify
 */
#include <sys/stat.h>

#include <string>
#include <vector>
#include <array>

#include "initialize.hh"
#include "sign.hh"
#include "verify.hh"

using std::array;
using std::cerr;
using std::cout;
using std::endl;
using std::string;
using std::vector;

void do_sign(int argc, char *argv[]) {
    if (argc != 5) {
        cout << endl
             << "Usage:" << endl
             << "\t./hardyhash sign <state_file> <message_file> <out_file>" << endl
             << endl
             << "\tstate_file must be a path to a valid signer state file." << endl
             << "\tmessage_file is the path to the message to be signed." << endl
             << "\tthe signature will be written to out_file." << endl
             << endl;
        exit(1);
    }
    string state_path = argv[2];
    string message_path = argv[3];
    string signature_path = argv[4];

    struct stat buf;
    if (stat(state_path.c_str(), &buf)) {
        cerr << endl
             << "ERROR: " << state_path << " does not exist." << endl
             << endl;
        exit(1);
    }
    if (stat(message_path.c_str(), &buf)) {
        cerr << endl
             << "ERROR: " << message_path << " does not exist." << endl
             << endl;
        exit(1);
    }
    if (stat(signature_path.c_str(), &buf) == 0) {
        cerr << endl
             << "ERROR: " << signature_path << " already exists." << endl
             << endl;
        exit(1);
    }

    vector<byte> message = read_file(message_path);
    signature_t signature = sign(state_path, message);

    write_signature(signature, signature_path);
}

void do_verify(int argc, char *argv[]) {
    if (argc != 5) {
        cout << endl
             << "Usage:" << endl
             << "\t./hardyhash verify <public_key> <message_file> <signature_file>" << endl
             << endl
             << "\tpublic_key must be a path to a public key file generated by 'initialize'." << endl
             << "\tmessage_file is the path to the message that had been signed." << endl
             << "\tsignature_file is a path to the signature on message_file." << endl
             << endl;
        exit(1);
    }
    string public_key = argv[2];
    string message_path = argv[3];
    string signature_path = argv[4];

    struct stat buf;
    if (stat(public_key.c_str(), &buf)) {
        cerr << endl
             << "ERROR: " << public_key << " does not exist." << endl
             << endl;
        exit(1);
    }
    if (stat(message_path.c_str(), &buf)) {
        cerr << endl
             << "ERROR: " << message_path << " does not exist." << endl
             << endl;
        exit(1);
    }
    if (stat(signature_path.c_str(), &buf)) {
        cerr << endl
             << "ERROR: " << signature_path << " does not exist." << endl
             << endl;
        exit(1);
    }

    array<byte, HASH_SIZE> pk = load_public_key(public_key);
    vector<byte> message = read_file(message_path);
    signature_t signature = load_signature(signature_path);

    bool success = verify(pk, message, signature);
    if (!success) {
        cout << "Verification failed." << endl;
        exit(1);
    }
    cout << "Verified successfully." << endl;
}

void do_initialize(int argc, char *argv[]) {
    if (argc != 6) {
        cout << endl
             << "Usage:" << endl
             << "\t./hardyhash initialize <lg_n_signers> <lg_messages_per_signer> <randomness> <output_dir>" << endl
             << endl
             << "\tlg_n_signers must be an even integer between 2 and 16, inclusive." << endl
             << "\tlg_messages_per_signer must be an even integer between 2 and 16, inclusive." << endl
             << "\trandomness should be a source of entropy, at most 1024 characters long." << endl
             << "\toutput_dir must be a path to the desired output directory, which must not exist." << endl
             << endl;
             exit(1);
    }
    size_t lg_n_signers = std::stoi(argv[2]);
    size_t lg_messages_per_signer = std::stoi(argv[3]);
    string randomness = argv[4];
    string out_dir = argv[5];

    if (lg_n_signers % 2 || lg_n_signers > 16 || lg_n_signers < 2) {
        cerr << endl
             << "ERROR: lg_n_signers must be an even integer between 2 and 16, inclusive." << endl
             << endl;
             exit(1);
    }

    if (lg_messages_per_signer % 2 || lg_messages_per_signer > 16 || lg_messages_per_signer < 2) {
        cerr << endl
             << "ERROR: lg_messages_per_signer must be an even integer between 2 and 16, inclusive." << endl
             << endl;
             exit(1);
    }

    struct stat buf;
    if (stat(out_dir.c_str(), &buf) == 0) {
        cerr << endl
             << "ERROR: output directory already exitsts."
             << endl;
        exit(1);
    }

    int status = mkdir(out_dir.c_str(), S_IRUSR | S_IWUSR | S_IXUSR);
    if (status) {
        cerr << endl
             << "ERROR: output directory could not be created."
             << endl;
        exit(1);
    }

    cout << "Initializing..." << endl;
    keys_t *k = initialize(lg_n_signers, lg_messages_per_signer,
                           reinterpret_cast<const byte *>(randomness.c_str()),
                           randomness.length());
    cout << "Writing signer states and public key to "
         << out_dir << " ..." << endl;
    write_signer_states(k, out_dir);
    cout << "Initialized successfully." << endl;
    delete k;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        cout << endl << "Usage: hardyhash COMMAND" << endl;
        cout << endl;
        cout << "Commands:" << endl;
        cout << "  initialize" << endl;
        cout << "  sign" << endl;
        cout << "  verify" << endl;
        cout << endl;
        cout << "Run `hardyhash COMMAND` with no arguments for more information about the command."
             << endl
             << endl;
        exit(1);
    }
    string command = argv[1];
    if (command == "initialize") {
        do_initialize(argc, argv);
    } else if (command == "sign") {
        do_sign(argc, argv);
    } else if (command == "verify") {
        do_verify(argc, argv);
    } else {
        cout << "Command must be one of 'initialize', 'sign', or 'verify'." << endl;
        exit(1);
    }
    return 0;
}
